spring:
  # thymeleaf??
  thymeleaf:
    # ????
    cache: false
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lzj_seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    # SpringBoot????????????????
    hikari:
      # ????
      pool-name: DateHikariCP
#      ?????
      minimum-idle: 5
#      ?????????????600000?10???
      idle-timeout: 1800000
#      ????????10
      maximum-pool-size: 10
#      ?????????????
      auto-commit: true
#      ?????????0?????????1800000?30???
      max-lifetime: 1800000
#      ?????????30000?30??
      connection-timeout: 30000
#      ?????????????
      connection-test-query: SELECT 1

#mybatis-plus??
mybatis-plus:
#  ??Mapper.xml????
  mapper-locations: classpath*:/mapper/*Mapper.xml
#  ??Mybatis?????????????????
  type-aliases-package: com.lzj_seckill.pojo

#Mybatis sql??????????????Mapper.xml?????
logging:
  level:
    com.lzj_seckill.mapper: debug
